spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kbabik@amelco.co.uk
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000